### ISSUE TITLE
Remove broken builds from Anaconda.org

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/xeus-cling-feedstock#23]
The build 0 of xeus-cling 0.8.1 is broken on both Linux and OS X.

`osx-64/xeus-cling-0.8.1-h7475705_0.tar.bz2`
`linux-64/xeus-cling-0.8.1-he513fc3_0.tar.bz2`

It would be fantastic if we could label these builds as broken.

cc @conda-forge/core

**Comment by ocefpaf** [comment]
Done. Let me know if I got the right ones.
https://anaconda.org/conda-forge/xeus-cling/files

**Comment by SylvainCorlay** [comment]
Yes! thanks @ocefpaf !
