### ISSUE TITLE
cxxopts should be a runtime dependency

### ISSUE THREAD

**Issue by dokempf** [conda-forge/xeus-cling-feedstock#42]
On a pristine conda installation of `xeus-cling`, running `find_package(xeus-cling)` from a CMake project fails, because `cxxopts` cannot be found. I think the reason is that the `cxxopts` dependency is marked `PUBLIC` in `xeus-cling`, but `cxxopts` is not treated as a runtime dependency in the feedstock.

FWIW, my reason to call `find_package(xeus-cling)` is to support installation of Doxygen tag files in this project: https://github.com/dokempf/xeus-cling-cmake-setup

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

    active environment : cling
    active env location : /home/dominic/anaconda3/envs/cling
    shell level : 3
       user config file : /home/dominic/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/dominic/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dominic/anaconda3/pkgs
                          /home/dominic/.conda/pkgs
       envs directories : /home/dominic/anaconda3/envs
                          /home/dominic/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/5.8.0-44-generic ubuntu/20.04.2 glibc/2.31
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False

```
</details>

**Comment by dokempf** [comment]
A tentative fix is https://github.com/dokempf/xeus-cling-feedstock/commit/cf3861418965c1f299ddf6e928018d715383e8b3 Unfortunately, I have no experience with conda packaging, so I don't know what else beyond this commit is necessary for a PR.

**Comment by JohanMabille** [comment]
Good catch! Indeed `cxxopts` should be listed as a run dependency. Your commit is exactly what needs to be done, would you like to open a PR?
